name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the 'main' branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.terrificfaiz }} # DockerHub username stored in GitHub secrets
        password: ${{ secrets.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 }} # DockerHub password stored in GitHub secrets

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: your-dockerhub-username/wisecow-app:latest

